baseURL = "https://nobelsmith.com/"
title = "Nobel Smith's Golf Journey"
theme = "PaperMod"
languageCode = "en-us"
defaultContentLanguage = "en"

# Enable emoji support
enableEmoji = true

# Enable Git info for last modified date
enableGitInfo = true

[params]
  # Site description
  description = "Follow my journey as a 10 handicap golfer, sharing experiences, tips, and stories from the course"
  author = "Nobel Smith"
  
  # Site header/navigation
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  # Social links
  [[params.socialIcons]]
    name = "email"
    url = "mailto:contact@nobelsmith.com"
    
[menu]
  [[menu.main]]
    identifier = "golf"
    name = "Golf"
    url = "/golf/"
    weight = 10
    
  [[menu.main]]
    identifier = "faith"
    name = "Faith"
    url = "/faith/"
    weight = 20
    
  [[menu.main]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts/"
    weight = 30
    
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40
    
[taxonomies]
  category = "categories"
  tag = "tags"
